name: mixmenu
description: MixMenu
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  #Packages Added Later on
  equatable: ^2.0.5
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  fpdart: ^1.1.0
  cached_network_image: ^3.2.3
  dart_rss: ^3.0.1
  flutter_screenutil: ^5.9.0
  html: ^0.15.4
  url_launcher: ^6.1.14

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/placeholder/
